### ISSUE TITLE
Import Error in python when built from source for cuda

### ISSUE THREAD

**Issue by skonb** [shinmorino/sqaod#50]
Do I have to build also for CPU?

```
ubuntu@ip-172-31-6-165:~$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
ubuntu@ip-172-31-6-165:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88

```

```
ubuntu@ip-172-31-6-165:~$ nvidia-smi
Wed Jun  6 09:24:09 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   39C    P8    30W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqaod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sqaod/__init__.py", line 10, in <module>
    from . import cpu
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sqaod/cpu/__init__.py", line 1, in <module>
    from . import formulas
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sqaod/cpu/formulas.py", line 4, in <module>
    from . import cpu_formulas as cext
ImportError: /home/ubuntu/anaconda3/lib/python3.6/site-packages/sqaod/cpu/cpu_formulas.so: undefined symbol: _ZN5sqaod12aligned_freeEPv
```

**Comment by shinmorino** [comment]
Did you clone from master branch?
P

**Comment by skonb** [comment]
Thanks yes.

**Comment by skonb** [comment]
Thanks! I'll check.

**Comment by skonb** [comment]
squad is installed on /bin/lib.
I already run ```sudo ldconfig```.

```locate sqaod``` only finds these
```
/etc/alternatives/libsqaodc.so.0
/etc/apt/sources.list.d/sqaod.list
/usr/lib/libsqaodc-avx2
/usr/lib/libsqaodc-sse2
/usr/lib/libsqaodc.so.0
/usr/lib/libsqaodc-avx2/libsqaodc.so.0
/usr/lib/libsqaodc-avx2/libsqaodc.so.0.0.0
/usr/lib/libsqaodc-sse2/libsqaodc.so.0
/usr/lib/libsqaodc-sse2/libsqaodc.so.0.0.0
/usr/share/doc/libsqaodc
/usr/share/doc/libsqaodc-avx2
/usr/share/doc/libsqaodc-sse2
/usr/share/doc/libsqaodc/changelog.Debian.gz
/usr/share/doc/libsqaodc/copyright
/usr/share/doc/libsqaodc-avx2/changelog.Debian.gz
/usr/share/doc/libsqaodc-avx2/copyright
/usr/share/doc/libsqaodc-sse2/changelog.Debian.gz
/usr/share/doc/libsqaodc-sse2/copyright
/var/cache/apt/archives/libsqaodc-avx2_0.2.0-0~xenial_amd64.deb
/var/cache/apt/archives/libsqaodc-sse2_0.2.0-0~xenial_amd64.deb
/var/cache/apt/archives/libsqaodc_0.2.0-0~xenial_amd64.deb
/var/lib/apt/lists/shinmorino.github.io_sqaod_ubuntu_dists_xenial_InRelease
/var/lib/apt/lists/shinmorino.github.io_sqaod_ubuntu_dists_xenial_multiverse_binary-amd64_Packages
/var/lib/dpkg/alternatives/libsqaodc.so.0
/var/lib/dpkg/info/libsqaodc-avx2.list
/var/lib/dpkg/info/libsqaodc-avx2.md5sums
/var/lib/dpkg/info/libsqaodc-avx2.postinst
/var/lib/dpkg/info/libsqaodc-avx2.prerm
/var/lib/dpkg/info/libsqaodc-avx2.shlibs
/var/lib/dpkg/info/libsqaodc-avx2.triggers
/var/lib/dpkg/info/libsqaodc-sse2.list
/var/lib/dpkg/info/libsqaodc-sse2.md5sums
/var/lib/dpkg/info/libsqaodc-sse2.postinst
/var/lib/dpkg/info/libsqaodc-sse2.prerm
/var/lib/dpkg/info/libsqaodc-sse2.shlibs
/var/lib/dpkg/info/libsqaodc-sse2.triggers
/var/lib/dpkg/info/libsqaodc.list
/var/lib/dpkg/info/libsqaodc.md5sums
```
Is this a problem?

**Comment by shinmorino** [comment]
Understand.  I'll test in my testbench.

**Comment by skonb** [comment]
Thanks!

Exactly what you describe was correct, and it now works.
Sorry for trouble you!

**Comment by shinmorino** [comment]
Good to know. 😄
